### ISSUE TITLE
CodeBlock starting with [

### ISSUE THREAD

**Issue by W4RH4WK** [vim-pandoc/vim-pandoc-syntax#129]
i just got a problem with my syntax highlighting using a codeblock which starts with a `[`. vim will not highlight it as a codeblock, while pandoc parses it as a codeblock. in the example below the second error line breaks my highlighting since there is also an `_` in it. everything returns to normal when the `[` is removed.

```
Meanwhile the `ff4d` script outputted various error messages like the
following.

    [ERROR] apiRequest failed. HTTPError: 404
    [ERROR] Could not fetch metadata for: /._encfs (Traceback (most recent call last):
      File "ff4d/ff4d.py", line 200, in getDropboxMetadata
        item = self.dbxMetadata(path)
      File "ff4d/ff4d.py", line 52, in dbxMetadata
        result = self.ar.get('https://api.dropbox.com/1/metadata/auto' + path, args)
      File "ff4d/ff4d.py", line 533, in get
        raise Exception, 'apiRequest failed. HTTPError: ' + str(e.code)
    Exception: apiRequest failed. HTTPError: 404
    )
```

**Comment by W4RH4WK** [comment]
great, thx :beers:
